### ISSUE TITLE
Question: should I add missing template sources here?

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags-template-source#2]
It looks like there are 3 templates in **ags-template-source** and 5 in **ags-templates**.

If I'm looking at updating the templates, should I commit the projects here for the two which are missing?
Presumably **ags-templates** is getting updated manually for build convenience, so I shouldn't be changing anything in there?

**Comment by morganwillcock** [comment]
Yes, that does sound a good idea. Do you know if the BASS one is also maintained? I was assuming not as it is set to 16 bit colour depth and uses the old `ProcessClick`.

**Comment by ivan-mogilko** [comment]
BASS is by Ghost (ags forum member) but I haven't heard from him in a while, and last we spoke he [permitted modifying the template](http://www.adventuregamestudio.co.uk/forums/index.php?topic=48441.msg636537585#msg636537585).

**Comment by morganwillcock** [comment]
One issue which I was not expecting, our Windows text encoding doesn't match. Any change I make through the Editor switches the encoding, so the commit is a full rewrite (changing from windows-1251 to windows-1252).

Is this something that needs looking at in the Editor before I update anything, or should I just re-commit all lines as 1252, or should should I try switching codepage to keep it in 1251?

**Comment by ivan-mogilko** [comment]
To think of it, making Editor save at least non-compiled data (script and game XML) in Unicode may be a good first feature for AGS 4. It needs strings in ANSI for compiled scripts and game data for the engine to be able to read them, but original scripts do not have to be ANSI.
That should also be possible to add wanted target locale to the game compiler settings.

**Comment by morganwillcock** [comment]
@dkrey should we try adding your templates as a sub-module?

**Comment by dkrey** [comment]
Yes, please go ahead.

**Comment by ivan-mogilko** [comment]
@dkrey , by the way, your template post on forums shows version of June 2018, yet the code in repository was last changed in 2017?

**Comment by dkrey** [comment]
Yep, I overlooked to build the new template for version 1.63 and to post it also in the thread.

**Comment by ivan-mogilko** [comment]
> Yep, I overlooked to build the new template for version 1.63 and to post it also in the thread.

Oh, so the template build in 2018 uses the source code from october 2017?

**Comment by dkrey** [comment]
Exactly. The template is more or less completed, so there isn't much I intend to add to modify. The tumbleweed template will be the place for new features and such.

**Comment by morganwillcock** [comment]
I've added the submodule reference, so I think this is now all of the template source files accessible from one place (so I should close this issue)?

**Comment by ivan-mogilko** [comment]
I forgot to ask, should we maybe consider newer AGS Tumbleweed template instead of original 9 verb?
Tbh I've never seen new one myself.

**Comment by morganwillcock** [comment]
Or if one does not replace the other, just include them both?

**Comment by ivan-mogilko** [comment]
> Or if one does not replace the other, just include them both?

I'll leave judgement to you, still haven't find time to check the new one :).

**Comment by morganwillcock** [comment]
I've not had a chance either, to be honest.
@dkrey is the plan for the newer template to eventually replace the older one?

**Comment by morganwillcock** [comment]
Okay, I've switched the submodule for the newer template.
I think all template sources are present now...
