### ISSUE TITLE
Possibly redundant cursor graphic change in BASS and VerbCoin

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-template-source#22]
This is bit confusing, both BASS and VerbCoin templates have this in GlobalScript:

<pre>
// open a GUI
function open_gui(GUI* gui_to_open)
{
  TwoClickHandler.Close();
  mouse.UseModeGraphic(eModeWalkto);
  gui_to_open.Visible = true;
}

// hide a GUI
function close_gui(GUI *gui_to_close)
{
  gui_to_close.Visible = false;
  mouse.UseDefaultGraphic();
}
</pre>

Note `mouse.UseModeGraphic` and `mouse.UseDefaultGraphic();`.

I am not certain if this is intended behavior for these UI style. Was the idea to have separate cursors or cursor graphics for when over room and over GUI?

**Comment by morganwillcock** [comment]
I think it is to ensure that a known cursor sprite is used for those GUIs, if the game had the cursor in some other mode.
