### ISSUE TITLE
TwoClickHandler: Cannot drop an item if you are over inventory GUI (solved)

### ISSUE THREAD

**Issue by Chombalmiron** [adventuregamestudio/ags-template-source#29]
I had a problem (at least for me it was) that, when I had an object selected and I had the pointer over the inventory gui, every time I right clicked, instead of " dropping" the object, I would observe (look at) what was under the pointer. And if I wanted to drop it, I had to pull down the menu and then do right click.

I was able to solve it by changing this in the template script:

{
    // right click to look at inventory item
 item.RunInteraction(eModeLookat);
 }

To this:

{
    // right click to look at inventory item
  if (player.ActiveInventory != null)
    player.ActiveInventory = null; 
  else{
  item.RunInteraction(eModeLookat);}
  }
}

Cheers!

**Comment by morganwillcock** [comment]
Thanks for reporting the problem.

I think it is configured to deselect the active inventory item if you click anywhere in the inventory window that is not over another inventory object, but how well that works likely depends on how large the window is and how large the inventory item sprites are. And logically it can be argued that the looking at the other inventory items does not occur within the context of the currently selected item, and so the looking doesn't make sense within the context of the cursor state/appearance,

I don't have access to the previous version of this module to double check what the previous version did, so I'll look to find a copy, but the VerbCoin module looks like it deselects the active inventory item when right-clicking on another item.

...so the more I think about it the more it feels correct to change it.

**Comment by Chombalmiron** [comment]
Yes, I don't see it as a problem per se, but a somewhat peculiar design decision.
As it comes by default, if you right click anywhere else on the screen except on the inventory it does deselect the item. So I think it's a bit counter-intuitive that it doesn't, and right where you need some agility to change items.

I decided to share this in case someone else finds it useful, if it brings an update of the template welcome! :D

**Comment by morganwillcock** [comment]
I think this is actually a mistake I made when translating the previous version into this one. Here is the code from the original:

```ags-script
	// Right Mouse Button on Inventory Item
	// when no inventory is selected:
	// - EXAMINE target
	// else
	// - DESELECT INVENTORY
	else if (button == eMouseRightInv)
	{
		if (player.ActiveInventory != null)
		{
			player.ActiveInventory = null;
			return;
		}
		
		InventoryItem *i = InventoryItem.GetAtScreenXY(mouse.x, mouse.y);
		if (i != null)
		{
			i.RunInteraction(eModeLookat);
		}
	}
```

I'll change the new one to match the behaviour of the old one.

**Comment by Chombalmiron** [comment]
Puede ser, justo hoy estaba jugando un juego de la 3.4.1 y no tenía ese problema con el inventario

**Comment by morganwillcock** [comment]
I've made the change here: https://github.com/adventuregamestudio/ags-template-source/commit/138f650492e8227f223614f81d12f63093bfe403
This will end up in the next rebuild of the templates which are supplied with the editor.
