### ISSUE TITLE
Add original graphic assets in the template sources

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-template-source#34]
**fix branch in development** : [ericoporto/ags-template-source/add-sprites](https://github.com/ericoporto/ags-template-source/tree/add-sprites)

---

After https://github.com/adventuregamestudio/ags/pull/1594 , we can now **not** store `acsprset.spr` file in the source control, and rely that the Editor will rebuild from the assets in the project folder.

If someone started a game based on a template, and do not fully replace the assets by their own, then rebuilding the `acsprset.spr` won't be possible, since there will be files from the template that aren't mapped to anyone in the project directory.

A possible solution to this, is to add a directory with a name like `Sprites` and place the template assets inside of it. 

It's good to think about the name because I imagine this will condition people who load the templates to place their own files in the same directory.

Ah, I do think we should ship the `acsprset.spr` with the templates (and so we should keep them here), I just think we should **also** ship the graphical assets outside of them too.

**Comment by ericoporto** [comment]
So, I think adding the sprite assets source is not enough, since we also need some way for the AGS Editor template exporting functionality to pick these up. :/

**Comment by ivan-mogilko** [comment]
> So, I think adding the sprite assets source is not enough, since we also need some way for the AGS Editor template exporting functionality to pick these up.

Please elaborate? Afaik template package may contain any files and subfolders, and all of them should be exported.

**Comment by ericoporto** [comment]
> Afaik template package may contain any files and subfolders, and all of them should be exported.

I didn't knew that. I am adding the original assets in place in the branch named [here](https://github.com/adventuregamestudio/ags-template-source/issues/34#issue-1194978937). Still need to figure out Thumbleweed.

**Comment by ivan-mogilko** [comment]
> > So, I think adding the sprite assets source is not enough, since we also need some way for the AGS Editor template exporting functionality to pick these up.
> 
> Please elaborate? Afaik template package may contain any files and subfolders, and all of them should be exported.

So, either I was wrong, or was thinking about something else, but AGS Editor does not package all existing folders inside the template file, but a hardcoded list of ones.

At the moment the only way to package templates exactly like you like is by using standalone tools (like agspak).

**Comment by ivan-mogilko** [comment]
Opened #40 instead in regards to the packaging problem.
