### ISSUE TITLE
VerbCoin: add a property to check current interaction mode

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-template-source#43]
This is based on a conversation with a user, it appears that VerbCoin does not let know which interaction has been triggered after it called a interaction callback. This makes it impossible to know current action if user uses one callback for multiple modes (similar to 9-verb).

I propose to add a readonly property called VerbCoin.CurrentAction, or similar, which would let know last run interaction.

**Comment by morganwillcock** [comment]
> This makes it impossible to know current action if user uses one callback for multiple modes (similar to 9-verb).

The design of the module is that all buttons use the same callback function; perhaps changes have already been made which make the situation more complicated. It seems a little strange to want to know the mode after the interaction was already run, isn't this going to be a cycle too late for some use cases?

If someone is effectively turning this into a different type of interface it would be easier to just customise the existing callback function, to read or modify the mode *before* the click is processed or let them cache the value themselves.
```diff
--- a/Verb Coin/VerbCoin.asc	
+++ b/Verb Coin/VerbCoin.asc	
@@ -163,7 +163,10 @@ static function VerbCoin::OnClick(GUIControl* control, MouseButton button)
 
   if (modemap != null && (button == eMouseLeft || button == eMouseRight))
   {
-    Room.ProcessClick(context_x, context_y, modemap[control.ID]);
+    CursorMode mode = modemap[control.ID];
+    // Do something with the mode here.
+    // ...
+    Room.ProcessClick(context_x, context_y, mode);
   }
 }
 
```
(Personally I'd rather keep the basic module as understandable as possible and encourage people to change it to meet their needs.)

**Comment by ivan-mogilko** [comment]
> read or modify the mode before the click is processed or let them cache the value themselves.

Right, this is what the user ended up with. I was thinking to let the module save this on its own.

> it would be easier to just customise the existing callback function

I just realized that 3.6.1 already allows to do this, because its interaction callbacks now look like
```
function Ego_Interact(Character *c, CursorMode mode)
```

So maybe this request is going to be redundant starting with 3.6.1.
