### ISSUE TITLE
Separate template versions for AGS 4

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-template-source#44]
If I understand correctly, the central ags CI now supports selecting a branch in the templates repository by name. It's then possible to have a separate branch for AGS 4 templates (in "ags4" branch).

It would be beneficial to have templates prepared for "ags4", with General Settings adjusted to avoid having backwards compatible values, such as using old compiler, and maybe something else (would need to run through the settings and see what else may have to be changed).

It would also be beneficial to replace any old-style script with a new-style and backport to 3.6.1 branch for easier managing of these versions.

Unfortunately, there's a blocking issue here: in ags4 the rooms are stored as subfolders, and template creation built in the Editor has a hardcoded list of files to package.
The existing options here are:
1. Hardcode new list of files in ags4 editor, suiting its needs: https://github.com/adventuregamestudio/ags/issues/2242
2. Resolve the feature proposal that would allow to have arbitrary files packaged in template: https://github.com/adventuregamestudio/ags/issues/2063
3. Package templates using a standalone tool, as it packages whole dir with subdirs.

Well, I guess the 1 is fastest, the 2 and 3 are something for the future.

**Comment by ericoporto** [comment]
Beyond these, is the loading of a template compatible with any of these options?

Also I wrote myself a fourth option, I added template export in my own tool, agstoolbox, for now [mimicking the AGS Editor hardcoded list](https://github.com/ericoporto/agstoolbox/blob/10b048259c93d78883e7f877164954a02e9d2161/src/agstoolbox/core/ags/ags_template.py#L42).

**Comment by ivan-mogilko** [comment]
> Beyond these, is the loading of a template compatible with any of these options?

I don't understand this question, could you elaborate?

**Comment by ericoporto** [comment]
Sure, I was unsure if the template extraction

https://github.com/adventuregamestudio/ags/blob/fc11710ab7bc32ce649f7ec6b9367a0bda952148/Editor/AGS.Native/agsnative.cpp#L401

Is indeed compatible with any methods or if there's something more there - like, if it for some reason wouldn't restore a game from a template if it had subfolders inside of it.

**Comment by ivan-mogilko** [comment]
Template extraction extracts everything found inside a template, including subfolders and files in subfolders.
There's no relevance to how (and using which method) the template was packed.

**Comment by ericoporto** [comment]
On the topic of ags4 templates, ags4 also shows a text description of template ([since this change](https://github.com/adventuregamestudio/ags/pull/1903)) so perhaps the template.txt files may need some adjustments - haven't actually checked, going by from memory.
