### ISSUE TITLE
Verb Coin: don't show verb coin if all buttons are disabled

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-template-source#50]
In verb coin template the coin buttons are optionally disabled if corresponding interaction is not available for the clicked object.
But it will still display a coin gui even if all buttons are disabled; user will see a fully disabled (or fully empty, depending on GUI disable style) disk.

I propose that in case all buttons got disabled, then the verb gui is not displayed at all.

---

An alternative to consider is to not display verb gui if there's no interactions, regardless of "disable buttons" setting. That is - if a clicked object has no interactions at all, then no verb gui is displayed, as a rule. This may be useful if there are hotspots or room objects that have special meaning (or used for animation), and not supposed to be interacted with.

A counter argument for the latter is a case when an object has no other interaction but "use inventory on". In which case showing verb coin with actions that do nothing may at least hint player that there are other ways to interact with this thing.

I guess, verb coin could test if "use inv" is also unavailable.

**Comment by ivan-mogilko** [comment]
Umh, upon trying this out, I found that there's another problem: unhandled_event still fires at any hotspot etc, even if it's not meant for interacting.

I am getting a feeling that it may not be just a issue with the template, but also the issue with Hotspots (specifically) not having Clickable flag. As there are other events than ones require clicking, it may be desirable to have a way to disable clicking interaction completely, but leave others, like "walking on". But then, there's "mouse over" event.... and a question whether it should trigger for "non-clickable" hotspots.

**Comment by AlanDrake** [comment]
A way to handle hotspots that should not need clicking is changing the cursor to walk mode when no relevant interactions are available on hover.

**Comment by ivan-mogilko** [comment]
> A way to handle hotspots that should not need clicking is changing the cursor to walk mode when no relevant interactions are available on hover.

It's not that... the question here is not "how to prevent an action", the question is "how to detect that action has to be prevented".

There's "unhandled_event" that is supposed to run if interaction is not provided too.

I suppose, the condition may be the absence of all standard interactions altogether, in which case click on the hotspot results in ProcessClick with WalkTo parameter.

**Comment by ivan-mogilko** [comment]
BASS template has the same issue, because it choses the action depending on what's under the cursor.

**Comment by ivan-mogilko** [comment]
Hm, maybe I am mixing multiple issues in this ticket. The original problem was to not show verb coin if all its interactions are disabled.

I could implement that, and fire a simple "interact" action instead of displaying a verb coin, leading to unhandled event.

Another issue mentioned here ("hidden" hotspots) might be dealt with separately. I'd need to rethink the problem and write a new ticket for that.

**Comment by ivan-mogilko** [comment]
Ok, I pushed this new property: 5d7cd005a73b383afbdbca7bfe433f79fda77621
it's off by default.

Frankly, after all the thinking, I now doubt in its usefullness, but it won't hurt to have it, I suppose.
