### ISSUE TITLE
automate releases of the templates

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-template-source#70]
after #27, the games in here are built with ags editor for checking - except Empty Game template, which will fail due to missing a room and having player character in room -1, it's still built but the error is ignored. Beyond this, the templates are built - they can be found int the "templates" artifact that is in an actions run like here https://github.com/adventuregamestudio/ags-template-source/actions/runs/11998186887

Now, these files need to go somewhere, either as releases here or to the specific branches in ags-template repository. I will probably try to put them in ags-template repository through automation eventually to avoid messing with the main repository for now.

Template build automation is only properly supported beyond ags editor 3.6.2.1 and 4.0.0.9, where the `/maketemplate` was added, so any previous release (like 3.6.1) won't be able to benefit from this. This should not be a big issue.

**Comment by ericoporto** [comment]
added a small commit (https://github.com/adventuregamestudio/ags-template-source/commit/2c34a503b9faa58fb331750a328ed8aa1418fef2) that `v.x.x.x.x` releases should upload to releases

**Comment by ivan-mogilko** [comment]
> @ivan-mogilko for this build with release to work it needs a specific permission in this [repository settings](https://github.com/adventuregamestudio/ags-template-source/settings/actions), in actions, Workflow permissions, it has to be set to Read and write permissions.

It's current set to "Read and write", not sure if it's default, or you set that yourself?

**Comment by ericoporto** [comment]
Nope, I don't have access to the settings in this repository. This should work, I am testing in my own repository.

**Comment by ericoporto** [comment]
OK, I tried a bunch of things and I kinda think the only way that will work is to use a PAT with our @ags-ci-user. I will think a bit more through the week if there is some way that doesn't require it, it's just that so far everything I tried failed to have the permissions to properly push things.

**Comment by ericoporto** [comment]
OK, the idea I have is to add the user @ags-templates-ci I created to the ags-templates repository as a commiter, and then add a PAT from this user as a secret in this repository as TEMPLATES_CI_TOKEN, and then I would use this user to push the templates in the ags-templates repository

**Comment by ericoporto** [comment]
I put a PR that implements this but I don't have the necessary credentials to configure this.

**Comment by ivan-mogilko** [comment]
> I put a PR that implements this but I don't have the necessary credentials to configure this.

I changed the "Templates commiter" team access to "Maintain", please tell if that's enough, if not I'll update to "Admin".
There's a roles access table in the github docs, but I can't really tell what is required for these actions:
https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#permissions-for-each-role

**Comment by ericoporto** [comment]
OK, I will configure, the idea is the ags-templates-ci gets it's token on the pipeline here and commit access on the ags-templates repo, and then the actions will use this user token for pushing the template updates there whenever a new release is created here.

**Comment by ivan-mogilko** [comment]
I have already invited ags-templates-ci to the repo with write access, but I could not figure out how to set this secret variable value (and also I'm concerned that if this is a secret variable maybe this should not be discussed in public?)

**Comment by ericoporto** [comment]
Ah, yeah, I can't mention the secret value here, I will configure it later - I also don't have it at hand right now, it's at home.

The only remaining thing after that, that kinda doesn't matter but it's only for our tracking of things is how we version the template source tags

- v.3.6.2.YYYY.MM.DD 
- v.3.6.2.0, 1, 2...
- Match the next version of AGS to be released (in the respective branch, like v.3.6.2.4)

**Comment by ivan-mogilko** [comment]
It's v3.6.*, without dots now, this tag syntax got changed around 3.6.0.

**Comment by ericoporto** [comment]
OK, I did the necessary configurations, I created two new releases, one for master, and one for ags4. It looks like it worked and pushed the respective commits.

**Comment by ivan-mogilko** [comment]
I noticed that the auto created templates have different names compared to previous existing. They have spaces in names replaced with dots.

This may be an issue, because when a user installs the new Editor to the same folder, new templates will not overwrite old ones, and they will have duplicates in template selection.

**Comment by ivan-mogilko** [comment]
I'm sorry, I got confused, and probably messing up certain things in my head.

I need to clarify once again: where does the Editor gets templates from now, is it [ags-templates](https://github.com/adventuregamestudio/ags-templates) repository, or ags-template-sources repository's latest Releases?

I noticed that the ags-templates repo received a CI commit, so this is where it updates them too.
The "dots" problem that I mentioned above only refers to ags-template-sources Releases. The files have old names in repository.

**Comment by ericoporto** [comment]
The ags repository gets them from the ags-templates, the ags-template-source commits to the appropriate branch on releases

**Comment by ivan-mogilko** [comment]
Ah, alright, i see now.

Why do the agt files have spaces replaced with dots in releases though, is this a CI doing or github is making changes?
e.g. here:
https://github.com/adventuregamestudio/ags-template-source/releases/tag/v4.0.0.2024.11.26

**Comment by ericoporto** [comment]
I have no idea, I will have to investigate, I didn't saw this before. :0

**Comment by ericoporto** [comment]
I quickly googled and it seems that GitHub replaces spaces with dots on upload. We don't use those files on upload yet, I think I can zip and push a zip package named ags-templates and then it will be alright. But this doesn't matter for the pipeline we have right now because the real thing goes through the ags-templates repository.

**Comment by ivan-mogilko** [comment]
I think zipping them for release would be a good idea anyway, because it's easier to download them all together.

**Comment by ericoporto** [comment]
I added a change that would zip the files and then changed to instead upload the zip of the templates

https://github.com/adventuregamestudio/ags-template-source/commit/163d84781f3432e53f7f30b3ea6898633346e3aa
